services:
  api-controle-carbono:
    container_name: fiap-api-controle-carbono
    build:
      context: ./Fiap.Api.ControleCarbono
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Fiap.Api.ControleCarbono/Logs:/app/Logs

  tests:
    build:
      context: .
      dockerfile: ./Fiap.Api.ControleCarbono.Tests/Dockerfile
    depends_on:
      - api-controle-carbono
    volumes:
      - ./Fiap.Api.ControleCarbono/TestResults:/src/TestResults