# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, Test and Deploy - ControleCarbono

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build Fiap.Api.ControleCarbono/Fiap.Api.ControleCarbono.csproj --configuration Release

      - name: Test
        run: dotnet test Fiap.Api.ControleCarbono.Tests/Fiap.Api.ControleCarbono.Tests.csproj --no-build --verbosity normal

      - name: Publish
        run: dotnet publish Fiap.Api.ControleCarbono/Fiap.Api.ControleCarbono.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08F040C36368436F80B927DED71529BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5313180F7FC7417E9EACFE856D6EDF22 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34B213D5FBE74FFEA04117777AE488BA }}

      - name: Deploy to Azure Web App Staging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ControleCarbono'
          slot-name: 'staging'
          package: .

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.ref == 'refs/heads/main' # Garante que o deploy em produção só ocorra a partir da branch main
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08F040C36368436F80B927DED71529BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5313180F7FC7417E9EACFE856D6EDF22 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34B213D5FBE74FFEA04117777AE488BA }}

      - name: Deploy to Azure Web App Production
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ControleCarbono'
          slot-name: 'Production'
          package: .
          